//! The `ProtonMail` MCP server handler: shared state, tool router, and the
//! `ServerHandler` implementation.
//!
//! The Proton [`Client`] is held lazily behind an async mutex and resumed on
//! first use. Destructive write tools are confirm-gated: unless the server was
//! started with `--allow-writes` or the call passes `confirm: true`, they
//! return a dry-run preview instead of performing the action.
//!
//! Each tool lives in its own module under [`crate::tools`]; this file just
//! sums their per-tool routers together and wires up the shared state and
//! transport.

use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::{tool_handler, ErrorData, ServerHandler};
use tokio::sync::Mutex;

use proton_core::Client;

use crate::common::not_authenticated;

/// Shared, cheaply-clonable server state.
#[derive(Clone)]
pub struct ProtonMail {
    pub(crate) state: Arc<AppState>,
    tool_router: ToolRouter<ProtonMail>,
}

pub(crate) struct AppState {
    /// The resumed Proton client (lazily initialised on first tool use).
    pub(crate) client: Mutex<Option<Client>>,
    /// Session profile to resume (created via `protonmail-cli login`).
    profile: String,
    needs_resume: AtomicBool,
    /// When true, destructive tools execute without requiring `confirm: true`.
    pub(crate) allow_writes: bool,
}

// --------------------------------------------------------------------------
// Construction & internal helpers
// --------------------------------------------------------------------------

impl ProtonMail {
    pub fn new(profile: String, allow_writes: bool) -> Self {
        // Combine the per-tool routers (each generated by a `#[tool_router]`
        // impl block in its own module) into the single dispatch router.
        let tool_router = Self::list_messages_router()
            + Self::search_messages_router()
            + Self::read_message_router()
            + Self::list_conversations_router()
            + Self::read_conversation_router()
            + Self::list_attachments_router()
            + Self::list_labels_router()
            + Self::send_message_router()
            + Self::reply_message_router()
            + Self::forward_message_router()
            + Self::cancel_scheduled_send_router()
            + Self::move_message_router()
            + Self::trash_message_router()
            + Self::mark_read_router()
            + Self::star_message_router()
            + Self::apply_label_router()
            + Self::remove_label_router()
            + Self::download_attachment_router()
            + Self::list_drafts_router()
            + Self::list_filters_router()
            + Self::list_contacts_router()
            + Self::list_addresses_router()
            + Self::search_local_router()
            + Self::save_draft_router()
            + Self::sync_cache_router()
            // message writes
            + Self::report_spam_router()
            + Self::report_ham_router()
            + Self::unsubscribe_router()
            + Self::empty_folder_router()
            + Self::delete_messages_router()
            + Self::undelete_messages_router()
            + Self::send_read_receipt_router()
            // drafts
            + Self::update_draft_router()
            + Self::delete_draft_router()
            // conversations
            + Self::search_conversations_router()
            + Self::move_conversation_router()
            + Self::trash_conversation_router()
            + Self::mark_conversation_router()
            + Self::star_conversation_router()
            + Self::snooze_conversation_router()
            + Self::unsnooze_conversation_router()
            // filters
            + Self::create_filter_router()
            + Self::check_filter_router()
            + Self::delete_filter_router()
            + Self::enable_filter_router()
            + Self::disable_filter_router()
            // labels / folders
            + Self::create_label_router()
            + Self::delete_label_router()
            + Self::update_label_router()
            // settings / addresses / contacts / counts / index
            + Self::get_settings_router()
            + Self::set_sign_router()
            + Self::set_attach_public_key_router()
            + Self::update_address_router()
            + Self::list_contact_emails_router()
            + Self::counts_router()
            + Self::index_cache_router();

        Self {
            state: Arc::new(AppState {
                client: Mutex::new(None),
                profile,
                needs_resume: AtomicBool::new(false),
                allow_writes,
            }),
            tool_router,
        }
    }

    /// Map a `proton-core` error into an MCP error, surfacing auth failures
    /// (no session / expired) as the actionable "not authenticated" message.
    pub(crate) fn map_err(&self, e: proton_core::Error) -> ErrorData {
        use proton_core::Error as E;
        match &e {
            E::Unauthorized => {
                self.state.needs_resume.store(true, Ordering::Relaxed);
                not_authenticated(&self.state.profile)
            }
            E::Api(api) if matches!(api.http_status, 401 | 403) => {
                self.state.needs_resume.store(true, Ordering::Relaxed);
                not_authenticated(&self.state.profile)
            }
            _ => ErrorData::internal_error(e.to_string(), None),
        }
    }

    /// Ensure the lazily-resumed client is present in `slot`.
    pub(crate) async fn ensure(&self, slot: &mut Option<Client>) -> Result<(), ErrorData> {
        if self.state.needs_resume.swap(false, Ordering::Relaxed) {
            *slot = None;
        }
        if slot.is_none() {
            let client = Client::resume_automated(&self.state.profile)
                .await
                .map_err(|e| self.map_err(e))?;
            *slot = Some(client);
        }
        Ok(())
    }

    /// Resolve a free-text reference (or exact id) to a message id.
    pub(crate) async fn resolve(
        &self,
        client: &Client,
        reference: &str,
    ) -> Result<String, ErrorData> {
        client
            .resolve_ref(reference)
            .await
            .map_err(|e| self.map_err(e))
    }

    /// Resolve a batch of references to ids.
    pub(crate) async fn resolve_all(
        &self,
        client: &Client,
        refs: &[String],
    ) -> Result<Vec<String>, ErrorData> {
        let mut ids = Vec::with_capacity(refs.len());
        for r in refs {
            ids.push(self.resolve(client, r).await?);
        }
        Ok(ids)
    }
}

// --------------------------------------------------------------------------
// ServerHandler (call_tool / list_tools / get_info generated by the macro)
// --------------------------------------------------------------------------

#[tool_handler(
    router = self.tool_router,
    name = "proton-mcp",
    instructions = "Proton Mail tools backed by a stored protonmail-cli session. Authenticate by running `protonmail-cli login` first; this server resumes that session. Read tools are always available. Destructive/structural write tools (send, reply, forward, cancel, move, trash, delete, empty-folder, undelete, spam/ham, unsubscribe, read-receipt, draft edit/delete, conversation move/trash, label apply/remove/create/delete/update, filter create/delete/enable/disable, settings, address update) return a dry-run preview unless called with confirm=true or the server was started with --allow-writes. Benign toggles (mark read/unread, star, snooze) and reads execute directly. Message tools accept free-text references resolved to ids; conversation/filter/label/draft tools take exact ids. Sending defaults to your primary address (first alias by Order) — pass `from` to use a different alias."
)]
impl ServerHandler for ProtonMail {}

// --------------------------------------------------------------------------
// HTTP transport
// --------------------------------------------------------------------------

/// Parse exact reverse-proxy authorities without weakening host validation.
fn allowed_http_hosts(value: &str) -> anyhow::Result<Vec<String>> {
    value
        .split(',')
        .map(|entry| {
            let host = entry.trim();
            anyhow::ensure!(
                !host.is_empty()
                    && !host.contains(['*', '@', '/', '\\', '?', '#'])
                    && !host.chars().any(char::is_whitespace),
                "allowed hosts must be exact authorities"
            );
            let authority = host
                .parse::<axum::http::uri::Authority>()
                .map_err(|_| anyhow::anyhow!("allowed hosts must be exact authorities"))?;
            anyhow::ensure!(
                !authority.host().is_empty()
                    && (authority.host() == host
                        || authority.port_u16().is_some_and(|port| port != 0)),
                "allowed hosts must have a valid hostname and port"
            );
            Ok(host.to_owned())
        })
        .collect()
}

/// Serve the MCP server over Streamable HTTP, mounted at `/mcp`.
pub async fn serve_http(server: ProtonMail, addr: &str, token: Arc<String>) -> anyhow::Result<()> {
    use rmcp::transport::streamable_http_server::{
        session::local::LocalSessionManager, StreamableHttpServerConfig, StreamableHttpService,
    };

    let mut config = StreamableHttpServerConfig::default();
    if let Ok(hosts) = std::env::var("PROTON_MCP_ALLOWED_HOST") {
        config.allowed_hosts.extend(allowed_http_hosts(&hosts)?);
    }
    let service = StreamableHttpService::new(
        move || Ok(server.clone()),
        Arc::new(LocalSessionManager::default()),
        config,
    );
    let app = axum::Router::new().nest_service("/mcp", service).layer(
        axum::middleware::from_fn_with_state(token, crate::http_auth::authorize),
    );
    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(listener, app).await?;
    Ok(())
}

// --------------------------------------------------------------------------
// Tests
// --------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_http_hosts_support_private_and_public_listeners() {
        assert_eq!(
            allowed_http_hosts("gx10-1.example.ts.net:9443, gx10-1.example.ts.net:10000").unwrap(),
            vec!["gx10-1.example.ts.net:9443", "gx10-1.example.ts.net:10000"]
        );
        assert_eq!(
            allowed_http_hosts("example.com").unwrap(),
            vec!["example.com"]
        );
        assert_eq!(
            allowed_http_hosts("[::1]:18765").unwrap(),
            vec!["[::1]:18765"]
        );
    }

    #[test]
    fn http_hosts_reject_wildcards_urls_and_malformed_entries() {
        for value in [
            "",
            ",example.com",
            "example.com,",
            "*.example.com",
            "https://example.com",
            "example.com/mcp",
            "user@example.com",
            "example.com?query",
            "example.com#fragment",
            "exam ple.com",
            "example.com\\mcp",
            "example.com:65536",
            "example.com:0",
            "example.com:not-a-port",
            "example.com\n:443",
        ] {
            assert!(allowed_http_hosts(value).is_err(), "accepted {value:?}");
        }
    }

    use rmcp::handler::server::wrapper::Parameters;
    use serde_json::json;

    use proton_core::Verdict;

    use crate::common::{excerpt, should_perform, signature_warning};
    use crate::tools::delete_messages::DeleteMessagesParams;
    use crate::tools::empty_folder::EmptyFolderParams;
    use crate::tools::move_conversation::MoveConversationParams;
    use crate::tools::move_message::MoveMessageParams;
    use crate::tools::send_message::SendMessageParams;

    const NO_SESSION_PROFILE: &str = "proton-mcp-test-nonexistent-profile-zz9q";

    #[test]
    fn gating_dry_run_when_not_allowed_and_unconfirmed() {
        // Default posture: no --allow-writes, no confirm => preview only.
        assert!(!should_perform(false, None));
        assert!(!should_perform(false, Some(false)));
        // Explicit confirm performs the action.
        assert!(should_perform(false, Some(true)));
        // --allow-writes performs regardless of confirm.
        assert!(should_perform(true, None));
        assert!(!should_perform(true, Some(false)));
    }

    #[test]
    fn excerpt_truncates_with_ellipsis() {
        assert_eq!(excerpt("hello", 10), "hello");
        let e = excerpt("hello world", 5);
        assert!(e.starts_with("hello"));
        assert!(e.ends_with('…'));
    }

    #[test]
    fn signature_warning_only_for_unverified() {
        assert!(signature_warning(Verdict::Verified).is_none());
        assert!(signature_warning(Verdict::Unsigned).is_some());
        assert!(signature_warning(Verdict::Unverified).is_some());
        assert!(signature_warning(Verdict::Invalid).is_some());
    }

    #[tokio::test]
    async fn tool_without_session_returns_not_authenticated() {
        let server = ProtonMail::new(NO_SESSION_PROFILE.to_string(), false);
        // A read tool with no stored session must surface the actionable error,
        // not panic.
        let err = match server.list_labels().await {
            Ok(_) => panic!("expected a not-authenticated error, got Ok"),
            Err(e) => e,
        };
        assert!(
            err.message.contains("Not authenticated"),
            "unexpected error message: {}",
            err.message
        );
        assert!(err.message.contains(NO_SESSION_PROFILE));
    }

    #[tokio::test]
    async fn send_returns_dry_run_preview_when_unconfirmed() {
        let server = ProtonMail::new(NO_SESSION_PROFILE.to_string(), false);
        let params = SendMessageParams {
            to: vec!["alice@example.com".to_string()],
            cc: Vec::new(),
            bcc: Vec::new(),
            from: None,
            subject: "Greetings".to_string(),
            body: "Hello there, this is the body.".to_string(),
            html: None,
            send_at: None,
            expires: None,
            confirm: None,
        };
        // No session is configured, but the dry-run path must short-circuit
        // before touching the client, so this succeeds without auth.
        let out = server
            .send_message(Parameters(params))
            .await
            .expect("dry-run preview should be Ok");
        let v = out.0;
        assert_eq!(v["dry_run"], json!(true));
        assert_eq!(v["action"], json!("send_message"));
        assert_eq!(v["preview"]["subject"], json!("Greetings"));
        assert_eq!(v["preview"]["to"][0], json!("alice@example.com"));
    }

    #[tokio::test]
    async fn organize_dry_run_preview_lists_ids_and_target() {
        let server = ProtonMail::new(NO_SESSION_PROFILE.to_string(), false);
        let params = MoveMessageParams {
            references: vec!["id-one".to_string(), "id-two".to_string()],
            folder: "archive".to_string(),
            confirm: None,
        };
        let out = server
            .move_message(Parameters(params))
            .await
            .expect("dry-run preview should be Ok");
        let v = out.0;
        assert_eq!(v["dry_run"], json!(true));
        assert_eq!(v["preview"]["folder"], json!("archive"));
        assert_eq!(v["preview"]["references"][1], json!("id-two"));
    }

    #[tokio::test]
    async fn empty_folder_dry_run_warns_and_does_not_perform() {
        // A permanent, irreversible action must short-circuit to a preview
        // (with a warning) when unconfirmed — never touching the client.
        let server = ProtonMail::new(NO_SESSION_PROFILE.to_string(), false);
        let out = server
            .empty_folder(Parameters(EmptyFolderParams {
                folder: "trash".to_string(),
                confirm: None,
            }))
            .await
            .expect("dry-run preview should be Ok");
        let v = out.0;
        assert_eq!(v["dry_run"], json!(true));
        assert_eq!(v["action"], json!("empty_folder"));
        assert_eq!(v["preview"]["folder"], json!("trash"));
        assert!(v["preview"]["warning"].is_string());
    }

    #[tokio::test]
    async fn delete_messages_dry_run_when_unconfirmed() {
        let server = ProtonMail::new(NO_SESSION_PROFILE.to_string(), false);
        let out = server
            .delete_messages(Parameters(DeleteMessagesParams {
                references: vec!["m1".to_string()],
                confirm: None,
            }))
            .await
            .expect("dry-run preview should be Ok");
        let v = out.0;
        assert_eq!(v["dry_run"], json!(true));
        assert_eq!(v["action"], json!("delete_messages"));
        assert_eq!(v["preview"]["references"][0], json!("m1"));
    }

    #[tokio::test]
    async fn move_conversation_dry_run_lists_ids_and_target() {
        let server = ProtonMail::new(NO_SESSION_PROFILE.to_string(), false);
        let out = server
            .move_conversation(Parameters(MoveConversationParams {
                ids: vec!["c1".to_string(), "c2".to_string()],
                folder: "archive".to_string(),
                confirm: None,
            }))
            .await
            .expect("dry-run preview should be Ok");
        let v = out.0;
        assert_eq!(v["dry_run"], json!(true));
        assert_eq!(v["action"], json!("move_conversation"));
        assert_eq!(v["preview"]["folder"], json!("archive"));
        assert_eq!(v["preview"]["ids"][1], json!("c2"));
    }
}
